<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-X3RK870BQE"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-X3RK870BQE');
        </script>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta property="og:locale" content="en_US" />
        <title>{{ $page['props']['openGraph']['title'] }} | Evergreen By Design</title>
        <meta name="description" content="{{ $page['props']['openGraph']['description'] }}">
        <link rel="icon" type="image/svg" href="{{ asset('media/images/svg/ebd-logo-rounded.svg') }}">


       
       
        
       
        <!-- Fonts -->
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="{{ asset('css/ebd-fonts.css') }}" />
        <link rel="canonical" href="https://evergreenbydesign.com{{ $page['url'] }}">

        

        <!-- Scripts -->
        @routes
        @vite(['resources/js/app.js', "resources/js/Pages/{$page['component']}.vue"])
        @inertiaHead

        @if( isset($page['props']['openGraph']) )
        <!-- Facebook Meta Tags -->
        <meta property='og:url' content="{{ $page['props']['ziggy']['location'] }}">
        <meta property='og:title' content="{{ $page['props']['openGraph']['title'] }}">
        <meta property='og:description' content="{{ $page['props']['openGraph']['description'] }}">
        <meta property="og:type" content="website" />
        <meta property='og:image' content="{{ $page['props']['openGraph']['imageUrl'] }}">

        <!-- Twitter Meta Tags -->
        <meta name='twitter:card' content='summary_large_image'>
        <meta property='twitter:domain' content="evergreenbydesign.com{{ $page['url'] }}">
        <meta property='twitter:url' content="https://evergreenbydesign.com{{ $page['url'] }}">
        <meta name='twitter:title' content="{{ $page['props']['openGraph']['title'] }}">
        <meta name='twitter:description' content="{{ $page['props']['openGraph']['description'] }}">
        <meta name='twitter:image' content="{{ $page['props']['openGraph']['imageUrl'] }}">

        <!-- Meta Tags Generated via DNSChecker.org -->
        @endif

        <!-- Meta Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s)
        {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};
        if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
        n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t,s)}(window, document,'script',
        'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '658906829085901');
        fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=658906829085901&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Meta Pixel Code -->
        <!-- JSON-LD Generated by: https://hallanalysis.com/json-ld-generator/ -->
        <script type='application/ld+json'> 
    {
        "@context": "http://www.schema.org",
        "@type": "ProfessionalService",
        "name": "Evergreen By Design",
        "url": "https://evergreenbydesign.com{{ $page['url'] }}",
        "telephone": "+5413785563",
        "priceRange": "$628.00",
        "logo": "https://evergreenbydesign.com/media/images/png/ebd-logo-rounded.png",
        "image": "https://evergreenbydesign.com/media/images/png/main-img.png",
        "description": "{{ $page['props']['openGraph']['description'] }}",
        "address": {
            "@type": "PostalAddress",
            "addressLocality": "Roseburg",
            "addressRegion": "Oregon",
            "postalCode": "97471",
            "addressCountry": "USA"
        },
        "geo": {
            "@type": "GeoCoordinates",
            "latitude": "{{ $page['props']['openGraph']['geo']['lat'] ? $page['props']['openGraph']['geo']['lat'] : ''}}",
            "longitude": "{{ $page['props']['openGraph']['geo']['long'] ? $page['props']['openGraph']['geo']['long'] : '' }}"
        },
        "openingHours": "Mo, Tu, We, Th, Fr 09:00-16:00",
        "contactPoint": {
            "@type": "ContactPoint",
            "telephone": "+1(541)378-5563",
            "contactType": "general"
        }
    }
        </script>
        
    </head>
    <body class="font-sans antialiased">
        @inertia
    </body>
</html>
